### ISSUE TITLE
OSError: libsvml.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tristanmtg** [SaifAati/Geospatial-COSICorr3D#11]
Hi,

I've been following the steps to install the Geospatial-COSICorr3D. After creating properly the conda environment, and adding the lines in the .bashrc file, try to run a simple correlation : 

correlation = Correlate(base_image_path=img1,
                        target_image_path=img2,
                        base_band=1,
                        target_band=1,
                        output_corr_path=indir,
                        corr_config=corr_config,
                        corr_show=False)
 
 But I get this error : 
 
 Correlation per tile:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/montagtr/Geospatial-COSICorr3D/geoCosiCorr3D/geoCore/core_correlation.py", line 107, in run_correlator
    lib_cfreq_corr = cdll.LoadLibrary(FREQ_CORR_LIB)
  File "/home/montagtr/anaconda3/envs/geoCosiCorr3D/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/montagtr/anaconda3/envs/geoCosiCorr3D/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libsvml.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/montagtr/PhD/phd-sandbox/sandbox.py", line 42, in <module>
    corr_show=False)
  File "/home/montagtr/Geospatial-COSICorr3D/geoCosiCorr3D/geoImageCorrelation/correlate.py", line 48, in __init__
    self.run_correlation()
  File "/home/montagtr/Geospatial-COSICorr3D/geoCosiCorr3D/geoImageCorrelation/correlate.py", line 155, in run_correlation
    ew_array, ns_array, snr_array = self.run_corr_engine(base_subset, target_subset)
  File "/home/montagtr/Geospatial-COSICorr3D/geoCosiCorr3D/geoImageCorrelation/correlate.py", line 192, in run_corr_engine
    mask_th=self.corr_engine.corr_params.mask_th)
  File "/home/montagtr/Geospatial-COSICorr3D/geoCosiCorr3D/geoCore/core_correlation.py", line 109, in run_correlator
    raise InvalidCorrLib
geoCosiCorr3D.geoCore.core_correlation.InvalidCorrLib

Do you have any idea where this could come from? 

Thanks for you help ! 

Tristan.

**Comment by rzinke** [comment]
Hello Tristan, I am having the same issue. Were you able to resolve this?

**Comment by tristanmtg** [comment]
Hello, sorry, I'm currently trying again by starting the installation from the beginning, but I still have the same error...

**Comment by SaifAati** [comment]
Great! The issue reported is that the shared libraries are not sourced correctly.
To resolve this you can set the `LD_LIBRARY_PATH` to include the necessary path by running `export LD_LIBRARY_PATH=~/Geospatial-COSICorr3D/lib/:$LD_LIBRARY_PATH`. This insures that the required libs are properly referenced
