### ISSUE TITLE
ValueError while orthorectification SPOT 6 imagery 

### ISSUE THREAD

**Issue by Alzahrani-Abdulsalam** [SaifAati/Geospatial-COSICorr3D#20]
I'm facing this issue while using geoCosiCorr3D orthorectification module for Spot 6 imagery using RSM  
```python
python3 ~/tools/Geospatial-COSICorr3D/scripts/cosicorr.py ortho IMG_SPOT6_P_202102010658122_SEN_PRODUCTION_20231115_061218_1.TIF --o_ortho ./R --gsd 6 --dem output_COP30.tif --debug RSM Spot6 DIM_SPOT6_P_202102010658122_SEN_PRODUCTION_20231115_061218_1.XML 
2024-05-19 11:16:28,092 [INFO] sat_model:SatModelParams(SAT_MODEL='RSM', METADATA='DIM_SPOT6_P_202102010658122_SEN_PRODUCTION_20231115_061218_1.XML', SENSOR='Spot6')
2024-05-19 11:16:36,370 [INFO] Input RSM sensor: Spot6
2024-05-19 11:16:36,370 [INFO] Satellite sensor:Spot6
2024-05-19 11:16:36,372 [INFO] DIM_SPOT6_P_202102010658122_SEN_PRODUCTION_20231115_061218_1.XML
2024-05-19 11:16:36,376 [INFO] ['Metadata_Identification', 'Dataset_Identification', 'Dataset_Content', 'Product_Information', 'Coordinate_Reference_System', 'Geoposition', 'Processing_Information', 'Raster_Data', 'Radiometric_Data', 'Geometric_Data', 'Quality_Assessment', 'Dataset_Sources']
2024-05-19 11:16:36,377 [INFO] mission:SPOT,instrument:6,imagingDate:2021-02-01, imagingTime:06:58:12.2,
2024-05-19 11:16:36,378 [INFO] sunAz:142.773,sunElev:38.7923, meanGSD:2.14588, time:2021-02-01T06:58:12.806000Z, satAlt:7.00471e+05, azAngle:177.708, viewAngle:2.90017, incidenceAngle:3.36472
2024-05-19 11:16:36,379 [INFO] nbCols:38609,nbRows:72849,nbBands:1
2024-05-19 11:16:36,379 [INFO] --- Get Spot Sensor Configuration ---
2024-05-19 11:16:36,380 [INFO] linePeriod:0.000229110269,startTime:2243314692.789776,endTimeLine:2243314709.48
2024-05-19 11:16:36,380 [INFO] focal[m]:3.760, detectorSize[m]:(col:8.337,row:8.337)
2024-05-19 11:16:36,381 [INFO] --- Get Look angles ----
2024-05-19 11:16:36,382 [INFO] Look_Angles:
[[-4.27997145e-02]
 [ 2.21714038e-06]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
2024-05-19 11:16:36,394 [INFO] --- Computing SPOT 6  RSM:
2024-05-19 11:16:36,394 [INFO]  *
Traceback (most recent call last):
  File "/home/iess/tools/Geospatial-COSICorr3D/scripts/cosicorr.py", line 236, in <module>
    cosicorr()
  File "/home/iess/tools/Geospatial-COSICorr3D/scripts/cosicorr.py", line 230, in cosicorr
    args.func(args)
  File "/home/iess/tools/Geospatial-COSICorr3D/scripts/cosicorr.py", line 64, in ortho_func
    orthorectify(args.input_img, o_ortho_path, ortho_params, None, args.dem, args.refine,
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoOrthoResampling/geoOrtho.py", line 607, in orthorectify
    ortho()
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoOrthoResampling/geoOrtho.py", line 58, in __call__
    self.orthorectify()
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoOrthoResampling/geoOrtho.py", line 61, in orthorectify
    self.model = self._get_rsm_model()
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoOrthoResampling/geoOrtho.py", line 137, in _get_rsm_model
    return RSM.build_RSM(metadata_file=self.metadata, sensor_name=self.sensor, debug=self.debug)
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoCore/core_RSM.py", line 52, in build_RSM
    rsm_sensor_model = cSpot67(dmpXml=metadata_file, debug=True)
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoRSM/Spot_RSM.py", line 89, in __init__
    self.Interpolate_position_velocity_attitude()
  File "/home/iess/tools/Geospatial-COSICorr3D/geoCosiCorr3D/geoRSM/Spot_RSM.py", line 168, in Interpolate_position_velocity_attitude
    self.interpSatPosition[:, i] = f1(self.linesDate)
  File "/home/iess/miniconda3/envs/geoCosiCorr3D/lib/python3.9/site-packages/scipy/interpolate/_polyint.py", line 81, in __call__
    y = self._evaluate(x)
  File "/home/iess/miniconda3/envs/geoCosiCorr3D/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 766, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/iess/miniconda3/envs/geoCosiCorr3D/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 799, in _check_bounds
    raise ValueError(f"A value ({above_bounds_value}) in x_new is above "
ValueError: A value (16.690224876111998) in x_new is above the interpolation range's maximum value (16.690224170684814).

```

**Comment by SaifAati** [comment]
This issue is related to the fact that the states provided in the metadata (.XML) do not cover the full image collection time range. To address this, I implemented a logic to support extrapolation of the states.
